services:
  - type: web
    name: tennis-predictor
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
